// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNPRGbt8DS82ZQWiXdrH4jI1GKF-YswY4',
    appId: '1:845963860540:web:e51728f1c390f5bf734139',
    messagingSenderId: '845963860540',
    projectId: 'realbirthapp-645e3',
    authDomain: 'realbirthapp-645e3.firebaseapp.com',
    storageBucket: 'realbirthapp-645e3.firebasestorage.app',
    measurementId: 'G-RYD6C97H62',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBydBOh_zxVAiV8tjW_8HLW-1tbbsjiDgc',
    appId: '1:845963860540:android:4fe9fa66e34f0da5734139',
    messagingSenderId: '845963860540',
    projectId: 'realbirthapp-645e3',
    storageBucket: 'realbirthapp-645e3.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwLl0Uz_7-Xu-lDF_x3nPazN7L95fU9_E',
    appId: '1:845963860540:ios:d06d74b176c42dc4734139',
    messagingSenderId: '845963860540',
    projectId: 'realbirthapp-645e3',
    storageBucket: 'realbirthapp-645e3.firebasestorage.app',
    iosBundleId: 'com.example.realBirthApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwLl0Uz_7-Xu-lDF_x3nPazN7L95fU9_E',
    appId: '1:845963860540:ios:d06d74b176c42dc4734139',
    messagingSenderId: '845963860540',
    projectId: 'realbirthapp-645e3',
    storageBucket: 'realbirthapp-645e3.firebasestorage.app',
    iosBundleId: 'com.example.realBirthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNPRGbt8DS82ZQWiXdrH4jI1GKF-YswY4',
    appId: '1:845963860540:web:4890d396b6153a32734139',
    messagingSenderId: '845963860540',
    projectId: 'realbirthapp-645e3',
    authDomain: 'realbirthapp-645e3.firebaseapp.com',
    storageBucket: 'realbirthapp-645e3.firebasestorage.app',
    measurementId: 'G-0BJHNWDQB1',
  );
}
